CREATE TABLE professores (
    id            NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(50) NOT NULL,
    sobrenome     VARCHAR2(50) NOT NULL,
    endereco      NUMBER NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    nascimento    DATE NOT NULL,
    nacionalidade VARCHAR2(50) NOT NULL,
    PRIMARY KEY ( id )
);

CREATE TABLE estudantes (
    id            NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(50) NOT NULL,
    sobrenome     VARCHAR2(50) NOT NULL,
    matricula     NUMBER NOT NULL,
    nascimento    DATE NOT NULL,
    nacionalidade VARCHAR2(50) NOT NULL,
    media         NUMBER,
    PRIMARY KEY ( id )
);

CREATE TABLE cursos (
    id         NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    nome       VARCHAR2(50) NOT NULL,
    codigo     VARCHAR2(10) NOT NULL,
    presencial NUMBER(1) NOT NULL,
    professor  NUMBER,
    max_alunos NUMBER NOT NULL,
    PRIMARY KEY ( id )
);