INSERT INTO ESTUDANTES (NOME, SOBRENOME,MATRICULA, NASCIMENTO, NACIONALIDADE, MEDIA)
VALUES ('Giovanni','Brito',15201748,'05/09/1996','Brasileiro', 8.8);
INSERT INTO ESTUDANTES (NOME, SOBRENOME,MATRICULA, NASCIMENTO, NACIONALIDADE, MEDIA)
VALUES ('Beatriz','Kanson',17103464,'19/06/1998','Brasileira', 9.4);
INSERT INTO ESTUDANTES (NOME, SOBRENOME,MATRICULA, NASCIMENTO, NACIONALIDADE, MEDIA)
VALUES ('Bruno','Leonardo',16205425,'21/03/1980','Brasileiro', 6.5);
commit;

INSERT INTO PROFESSORES (NOME, SOBRENOME, ENDERECO, EMAIL, NASCIMENTO, NACIONALIDADE)
VALUES ('Alan','Nakamura',1,'alan.nakamura@email.com','14/06/1965','Brasileiro');
INSERT INTO PROFESSORES (NOME, SOBRENOME, ENDERECO, EMAIL, NASCIMENTO, NACIONALIDADE)
VALUES ('Andrea','Piga',2,'andrea.piga@email.com','07/07/1972','Italiano');
INSERT INTO PROFESSORES (NOME, SOBRENOME, ENDERECO, EMAIL, NASCIMENTO, NACIONALIDADE)
VALUES ('Salma','Helena',3,'salma.helena@email.com','05/11/1979','Brasileira');
commit;

INSERT INTO CURSOS (NOME, CODIGO, PRESENCIAL, PROFESSOR, MAX_ALUNOS)
VALUES ('Mecânica dos Sólidos', 'MECSOL1', 1, 2, 50);
INSERT INTO CURSOS (NOME, CODIGO, PRESENCIAL, PROFESSOR, MAX_ALUNOS)
VALUES ('Cálculo I', 'CALC1', 1, 3, 100);
INSERT INTO CURSOS (NOME, CODIGO, PRESENCIAL, PROFESSOR, MAX_ALUNOS)
VALUES ('Física III', 'FIS3', 1, 1, 100);
commit;

INSERT INTO MATRICULAS(ID_ALUNO,ID_CURSO,MEDIA)
VALUES (1,1,7.5);
INSERT INTO MATRICULAS(ID_ALUNO,ID_CURSO,MEDIA)
VALUES(2,3,10);
INSERT INTO MATRICULAS(ID_ALUNO,ID_CURSO,MEDIA)
VALUES(3,2,4.5);
commit;